export const ssembol = [
    /* AAAAA */
    { name: "APTUSDT", text: "Aptos" },
    { name: "AVAXUSDT", text: "Avalanche" },
    { name: "APEUSDT", text: "ApeCoin" },
    { name: "ALGOUSDT", text: "Algorand" },
    { name: "AXSUSDT", text: "Axie Infinity" },
    { name: "ARUSDT", text: "Arweave" },
    { name: "TLMUSDT", text: "Alien Worlds" },
    { name: "AAVEUSDT", text: "Aave" },
    { name: "ANKRUSDT", text: "Ankr" },
    { name: "ANCUSDT", text: "Anchor Protocol" },
    { name: "AUDIOUSDT", text: "Audius" },
    { name: "AGLDUSDT", text: "Adventure Gold" },
    { name: "ACHUSDT", text: "Alchemy Pay" },
    { name: "ALPINEUSDT", text: "Alpine F1 Team Fan Token" },
    { name: "ATAUSDT", text: "Automata Network" },
    { name: "ADADOWNUSDT", text: "ADADOWN" },
    { name: "AMBUSDT", text: "AirDAO" },
    { name: "ASRUSDT", text: "AS Roma Fan Token" },
    { name: "ANTUSDT", text: "Aragon" },
    { name: "ALPHAUSDT", text: "Alpha Venture DAO" },
    { name: "ARPAUSDT", text: "ARPA" },
    { name: "ADAUPUSDT", text: "ADAUP" },
    { name: "API3USDT", text: "API3" },
    { name: "AMPUSDT", text: "Amp" },
    { name: "AERGOUSDT", text: "Aergo" },
    { name: "ASTRUSDT", text: "Astar" },
    { name: "ATMUSDT", text: "Atletico De Madrid Fan Token" },
    { name: "ACAUSDT", text: "Acala Token" },
    { name: "ALPACAUSDT", text: "Alpaca Finance" },
    { name: "REPUSDT", text: "Augur" },
    { name: "ADXUSDT", text: "Ambire AdEx" },
    { name: "ACMUSDT", text: "AC Milan Fan Token" },
    { name: "AIONUSDT", text: "Aion" },
    { name: "ASTUSDT", text: "AirSwap" },
    { name: "AKROUSDT", text: "Akropolis" },
    { name: "ALCXUSDT", text: "Alchemix" },
    { name: "ELFUSDT", text: "aelf" },
    { name: "AUTOUSDT", text: "Auto" },
    { name: "ARDRUSDT", text: "Ardor" },
    { name: "GHSTUSDT", text: "Aavegotchi" },
    { name: "FORTHUSDT", text: "Ampleforth Governance Token" },
    /* BBBBB */
    { name: "BTCUSDT", text: "Bitcoin Coin" },
    { name: "BNBUSDT", text: "BNB Coin" },
    { name: "BUSDUSDT", text: "Binance USD " },
    { name: "BETHUSDT", text: "Beacon ETH" },
    { name: "BCHUSDT", text: "Bitcoin Cash" },
    { name: "BAKEUSDT", text: "BakeryToken" },
    { name: "BTGUSDT", text: "Bitcoin Gold" },
    { name: "BATUSDT", text: "Basic Attention Token" },
    { name: "BURGERUSDT", text: "BurgerCities" },
    { name: "BLZUSDT", text: "Bluzelle" },
    { name: "BNXUSDT", text: "BinaryX" },
    { name: "BANDUSDT", text: "Band Protocol" },
    { name: "BELUSDT", text: "Bella Protocol" },
    { name: "BETAUSDT", text: "Beta Finance" },
    { name: "BSWUSDT", text: "Biswap" },
    { name: "BTCDOWNUSDT", text: "BTCDOWN" },
    { name: "BTCSTUSDT", text: "Bitcoin Standard Hashrate Token" },
    { name: "BTTCUSDT", text: "BitTorrent-New" },
    { name: "BONDUSDT", text: "BarnBridge" },
    { name: "AUCTIONUSDT", text: "Bounce Governance Token" },
    { name: "BNBDOWNUSDT", text: "BNBDOWN" },
    { name: "BNTUSDT", text: "Bancor" },
    { name: "BIFIUSDT", text: "Beefy Finance" },
    { name: "QIUSDT", text: "BENQI" },
    { name: "BALUSDT", text: "Balancer" },
    { name: "BADGERUSDT", text: "Badger DAO" },
    { name: "BICOUSDT", text: "Biconomy" },
    { name: "BNBUPUSDT", text: "BNBUP" },
    { name: "FIDAUSDT", text: "Bonfida" },
    { name: "BEAMUSDT", text: "Beam" },
    { name: "BTCUPUSDT", text: "BTCUP" },
    { name: "BTSUSDT", text: "BitShares" },
    /* CCCCC */
    { name: "ATOMUSDT", text: "Cosmos " },
    { name: "ADAUSDT", text: "Cardano" }, 
    { name: "CRVUSDT", text: "Curve DAO Token" },
    { name: "PEOPLEUSDT", text: "ConstitutionDAO" },
    { name: "C98USDT", text: "Coin98" },
    { name: "COMPUSDT", text: "Compound" },
    { name: "CHZUSDT", text: "Chiliz" },
    { name: "COCOSUSDT", text: "Cocos-BCX" },
    { name: "COTIUSDT", text: "COTI" },
    { name: "CELOUSDT", text: "Celo" },
    { name: "CELRUSDT", text: "Celer Network" },
    { name: "CHRUSDT", text: "Chromia" },
    { name: "CTSIUSDT", text: "Cartesi" },
    { name: "CLVUSDT", text: "CLV" },
    { name: "CVXUSDT", text: "Convex Finance" },
    { name: "CVCUSDT", text: "Civic" },
    { name: "CTXCUSDT", text: "Cortex" },
    { name: "CREAMUSDT", text: "Cream Finance" },
    { name: "CFXUSDT", text: "Conflux" },
    { name: "COSUSDT", text: "Contentos" },
    /* DDDDD */
    { name: "DOGEUSDT", text: "DogeCoin" },
    { name: "DENTUSDT", text: "Dent" },
    { name: "YFIIUSDT", text: "DFI.Money" },
    { name: "DYDXUSDT", text: "dYdX" },
    { name: "MANAUSDT", text: "Decentraland" },
    { name: "DNTUSDT", text: "district0x" },
    { name: "DASHUSDT", text: "Dash" },
    { name: "DUSKUSDT", text: "Dusk Network" },
    { name: "DFUSDT", text: "dForce" },
    { name: "DREPUSDT", text: "Drep [new]" },
    { name: "DODOUSDT", text: "DODO" },
    { name: "DOTDOWNUSDT", text: "DOTDOWN" },
    { name: "DOTUPUSDT", text: "DOTUP" },
    { name: "DEGOUSDT", text: "Dego Finance" },
    { name: "DGBUSDT", text: "DigiByte" },
    { name: "DIAUSDT", text: "DIA" },
    { name: "DCRUSDT", text: "Decred" },
    { name: "DOCKUSDT", text: "Dock" },
    { name: "DEXEUSDT", text: "DeXe" },
    /* E */
    { name: "ETHUSDT", text: "Etherum" },
    { name: "ETHDOWNUSDT", text: "ETHDOWN" },
    { name: "MLNUSDT", text: "Enzyme" },
    { name: "XECUSDT", text: "eCash" },
    { name: "ETCUSDT", text: "Ethereum Classic " },
    { name: "EOSUSDT", text: "EOS" },
    { name: "ENJUSDT", text: "Enjin Coin" },
    { name: "EGLDUSDT", text: "Elrond" },
    { name: "ENSUSDT", text: "Ethereum Name Service" },
    { name: "ERNUSDT", text: "Ethernity" },
    { name: "ETHUPUSDT", text: "ETHUP" },
    { name: "EPXUSDT", text: "Ellipsis" },
    /* F */
    { name: "FORUSDT", text: "ForTube" },
    { name: "FLMUSDT", text: "Flamingo" },
    { name: "FRONTUSDT", text: "Frontier" },
    { name: "FLUXUSDT", text: "Flux" },
    { name: "FIROUSDT", text: "Firo" },
    { name: "FIOUSDT", text: "FIO Protocol" },
    { name: "FUNUSDT", text: "FUNToken" },
    { name: "FETUSDT", text: "Fetch.ai" },
    { name: "BARUSDT", text: "FC Barcelona Fan Token" },
    { name: "FILUSDT", text: "Filecoin " },
    { name: "FTMUSDT", text: "Fantom" },
    { name: "FTTUSDT", text: "FTX Token" },
    { name: "PORTOUSDT", text: "FC Porto Fan Token" },
    { name: "FLOWUSDT", text: "Flow" },
    { name: "FXSUSDT", text: "Frax Share" },
    /* G */
    { name: "GTOUSDT", text: "Gifto" }, 
    { name: "GNOUSDT", text: "Gnosis" }, 
    { name: "GTCUSDT", text: "Gitcoin" },
    { name: "GMXUSDT", text: "GMX" },
    { name: "GALAUSDT", text: "Gala " },
    { name: "GALUSDT", text: "Galxe" },
    { name: "GASUSDT", text: "Gas" },
    { name: "GLMUSDT", text: "Golem" },
    /* H */
    { name: "HBARUSDT", text: "Hedera" }, 
    { name: "FARMUSDT", text: "Harvest Finance" }, 
    { name: "ONEUSDT", text: "Harmony" },
    { name: "HOTUSDT", text: "Holo" },
    { name: "HNTUSDT", text: "Helium" },
    { name: "HIGHUSDT", text: "Highstreet" },
    { name: "ZENUSDT", text: "Horizen" },
    { name: "HIVEUSDT", text: "Hive" },
    { name: "MFTUSDT", text: "Hifi Finance" },
    /* I */
    { name: "ILVUSDT", text: "Illuvium" },
    { name: "IOTAUSDT", text: "IOTA" },
    { name: "IOTXUSDT", text: "IoTeX" },
    { name: "RLCUSDT", text: "iExec RLC" },
    { name: "IMXUSDT", text: "ImmutableX" },
    { name: "INJUSDT", text: "Injective" },
    { name: "ICPUSDT", text: "Internet Computer" },
    { name: "IOSTUSDT", text: "IOST" },
    { name: "IDEXUSDT", text: "IDEX" },
    { name: "ICXUSDT", text: "ICON" },
    { name: "IQUSDT", text: "IQ" },
    { name: "IRISUSDT", text: "IRISnet" },
    /* J */
    { name: "JOEUSDT", text: "JOE" },
    { name: "JUVUSDT", text: "Juventus Fan Token" },
    { name: "JSTUSDT", text: "JUST" },
    { name: "JASMYUSDT", text: "JasmyCoin " },
    /* K */
    { name: "KDAUSDT", text: "Kadena" }, 
    { name: "KSMUSDT", text: "Kusama" },
    { name: "KNCUSDT", text: "Kyber Network Crystal v2" },
    { name: "KLAYUSDT", text: "Klaytn" },
    { name: "KAVAUSDT", text: "Kava" },
    { name: "KMDUSDT", text: "Komodo" },
    { name: "KP3RUSDT", text: "Keep3rV1" },
    { name: "HARDUSDT", text: "Kava Lend" },
    /* L */
    { name: "LTCUSDT", text: "LiteCoin" },
    { name: "LINKDOWNUSDT", text: "LINKDOWN" },
    { name: "LINAUSDT", text: "Linear Finance" },
    { name: "LINKUSDT", text: "logo Chainlink" },
    { name: "LRCUSDT", text: "Loopring" },
    { name: "LITUSDT", text: "Litentry" },
    { name: "LTOUSDT", text: "LTO Network" },
    { name: "LEVERUSDT", text: "LeverFi" },
    { name: "LOKAUSDT", text: "League of Kingdoms Arena" },
    { name: "LINKUPUSDT", text: "LINKUP" },
    { name: "LDOUSDT", text: "Lido DAO" },
    { name: "LSKUSDT", text: "Lisk" },
    { name: "LOOMUSDT", text: "Loom Network" },
    { name: "LPTUSDT", text: "Livepeer" },
    /* M */
    { name: "MTLUSDT", text: "Metal DAO" },
    { name: "MKRUSDT", text: "Maker" },
    { name: "CITYUSDT", text: "Manchester City Fan Token" },
    { name: "ALICEUSDT", text: "MyNeighborAlice" },
    { name: "MASKUSDT", text: "Mask Network" },
    { name: "MIRUSDT", text: "Mirror Protocol" },
    { name: "MINAUSDT", text: "Mina" },
    { name: "MBOXUSDT", text: "MOBOX" },
    { name: "MDXUSDT", text: "Mdex" },
    { name: "DARUSDT", text: "Mines of Dalarnia" },
    { name: "XMRUSDT", text: "Monero" },
    { name: "GLMRUSDT", text: "Moonbeam" },
    { name: "MOVRUSDT", text: "Moonriver" },
    { name: "MITHUSDT", text: "Mithril" },
    { name: "PONDUSDT", text: "Marlin" },
    { name: "MDTUSDT", text: "Measurable Data Token" },
    { name: "MBLUSDT", text: "MovieBloc" },
    { name: "MOBUSDT", text: "MobileCoin" },
    { name: "MCUSDT", text: "Merit Circle" },
    { name: "MULTIUSDT", text: "Multichain" },
    /* N */
    { name: "XEMUSDT", text: "NEM" },
    { name: "CKBUSDT", text: "Nervos Network" },
    { name: "NULSUSDT", text: "NULS" },
    { name: "NEBLUSDT", text: "Neblio" },
    { name: "NBSUSDT", text: "New BitShares" },
    { name: "NEARUSDT", text: "NEAR Protocol" },
    { name: "NEOUSDT", text: "Neo" },
    { name: "NKNUSDT", text: "NKN" },
    { name: "NEXOUSDT", text: "Nexo" },
    { name: "XNOUSDT", text: "Nano" },
    /* O */
    { name: "ONTUSDT", text: "Ontology" },
    { name: "OCEANUSDT", text: "Ocean Protocol" },
    { name: "ORNUSDT", text: "Orion Protocol" },
    { name: "OSMOUSDT", text: "Osmosis" },
    { name: "OPUSDT", text: "Optimism" },
    { name: "ROSEUSDT", text: "Oasis Network" },
    { name: "OGNUSDT", text: "Origin Protocol" },
    { name: "OMGUSDT", text: "OMG Network" },
    { name: "OGUSDT", text: "OG Fan Token" },
    { name: "OOKIUSDT", text: "Ooki Protocol" },
    { name: "ONGUSDT", text: "Ontology Gas" },
    { name: "OXTUSDT", text: "Orchid" },
    { name: "OAXUSDT", text: "OAX" },
    /* P */
    { name: "DOTUSDT", text: "Polkadot " },
    { name: "POLYXUSDT", text: "Polymesh" },
    { name: "PHAUSDT", text: "Phala Network" },
    { name: "POLYUSDT", text: "Polymath" },
    { name: "CAKEUSDT", text: "PancakeSwap" },
    { name: "MATICUSDT", text: "Polygon" },
    { name: "PSGUSDT", text: "Paris Saint-Germain Fan Token" },
    { name: "PERPUSDT", text: "Perpetual Protocol" },
    { name: "PROSUSDT", text: "Prosper" },
    { name: "CVPUSDT", text: "PowerPool" },
    { name: "PHBUSDT", text: "Phoenix" },
    { name: "PUNDIXUSDT", text: "Pundi X (New)" },
    { name: "PIVXUSDT", text: "PIVX" },
    { name: "PLAUSDT", text: "PlayDapp" },
    { name: "POWRUSDT", text: "Powerledger" },
    { name: "POLSUSDT", text: "Polkastarter" },
    { name: "PROMUSDT", text: "Prom" },
    { name: "PNTUSDT", text: "pNetwork" },
    { name: "PAXGUSDT", text: "PAX Gold" },
    { name: "PERLUSDT", text: "PERL.eco" },
    /* Q */
    { name: "QKCUSDT", text: "QuarkChain" },
    { name: "QTUMUSDT", text: "Qtum" },
    { name: "QNTUSDT", text: "Quant" },
    { name: "QLCUSDT", text: "QLC Chain" },
    { name: "QUICKUSDT", text: "QuickSwap" },
    /* R */
    { name: "RAYUSDT", text: "Raydium" },
    { name: "REQUSDT", text: "Request" },
    { name: "RNDRUSDT", text: "Render Token" },
    { name: "RADUSDT", text: "Radicle" },
    { name: "RSRUSDT", text: "Reserve Rights" },
    { name: "RVNUSDT", text: "Ravencoin" },
    { name: "REEFUSDT", text: "Reef" },
    { name: "REIUSDT", text: "REI Network" },
    { name: "RIFUSDT", text: "RSK Infrastructure Framework" },
    { name: "RENUSDT", text: "Ren" },
    /* S */
    { name: "SOLUSDT", text: "SolanaCoin" },
    { name: "SHIBUSDT", text: "Shiba Inu " },
    { name: "SUSHIUSDT", text: "SushiSwap " },
    { name: "SPELLUSDT", text: "Spell Token" },
    { name: "SANTOSUSDT", text: "Santos FC Fan Token" },
    { name: "SLPUSDT", text: "Smooth Love Potion" },
    { name: "SNXUSDT", text: "Synthetix" },
    { name: "XLMUSDT", text: "Stellar" },
    { name: "STGUSDT", text: "Stargate Finance" },
    { name: "SRMUSDT", text: "Serum" },
    { name: "SKLUSDT", text: "SKALE" },
    { name: "SXPUSDT", text: "SXP" },
    { name: "LAZIOUSDT", text: "S.S. Lazio Fan Token" },
    { name: "GMTUSDT", text: "STEPN" },
    { name: "STORJUSDT", text: "Storj" },
    { name: "SFPUSDT", text: "SafePal" },
    { name: "STMXUSDT", text: "StormX" },
    { name: "CTKUSDT", text: "Shentu" },
    { name: "SSVUSDT", text: "ssv.network" },
    { name: "SNMUSDT", text: "SONM (BEP-20)" },
    { name: "SUNUSDT", text: "Sun (New)" },
    { name: "AGIXUSDT", text: "SingularityNET" },
    { name: "SUPERUSDT", text: "SuperFarm" },
    { name: "SYSUSDT", text: "Syscoin" },
    { name: "SCRTUSDT", text: "Secret" },
    { name: "KEYUSDT", text: "SelfKey" },
    { name: "FISUSDT", text: "StaFi" },
    { name: "STXUSDT", text: "Stacks" },
    { name: "STRAXUSDT", text: "Stratis" },
    { name: "STEEMUSDT", text: "Steem" },
    { name: "DATAUSDT", text: "Streamr" },
    { name: "RAREUSDT", text: "SuperRare" },
    { name: "STPTUSDT", text: "STP" },
    { name: "SCUSDT", text: "Siacoin" },
    /* T */
    { name: "USTCUSDT", text: "TerraClassicUSD" },
    { name: "TRXUSDT", text: "TRON" },
    { name: "LUNAUSDT", text: "Terra" },
    { name: "LUNCUSDT", text: "Terra Classic" },
    { name: "SANDUSDT", text: "The Sandbox" },
    { name: "THETAUSDT", text: "Theta Network" },
    { name: "TFUELUSDT", text: "Theta Fuel" },
    { name: "RUNEUSDT", text: "THORChain" },
    { name: "XTZUSDT", text: "Tezos" },
    { name: "TRBUSDT", text: "Tellor" },
    { name: "TWTUSDT", text: "Trust Wallet Token" },
    { name: "TCTUSDT", text: "TokenClub" },
    { name: "TRUUSDT", text: "TrueFi" },
    { name: "TORNUSDT", text: "Tornado Cash" },
    { name: "GRTUSDT", text: "The Graph" },
    { name: "CHESSUSDT", text: "Tranchess" },
    { name: "TKOUSDT", text: "Toko Token" },
    { name: "TOMOUSDT", text: "TomoChain" },
    { name: "TUSDT", text: "Threshold" },
    { name: "TRXDOWNUSDT", text: "TRXDOWN" },
    { name: "TROYUSDT", text: "TROY" },
    { name: "TRIBEUSDT", text: "Tribe" },
    { name: "AVAUSDT", text: "Travala.com" },
    /* U */
    { name: "UTKUSDT", text: "Utrust" },
    { name: "UFTUSDT", text: "UniLend" },
    { name: "UNIUSDT", text: "Uniswap" },
    { name: "UMAUSDT", text: "UMA" },
    { name: "UNFIUSDT", text: "Unifi Protocol DAO" },
    /* V */
    { name: "VIBUSDT", text: "Viberate" },
    { name: "VIDTUSDT", text: "VIDT DAO" },
    { name: "PYRUSDT", text: "Vulcan Forged PYR" },
    { name: "VETUSDT", text: "VeChain" },
    { name: "VITEUSDT", text: "VITE" },
    { name: "TVKUSDT", text: "Virtua" },
    { name: "VGXUSDT", text: "Voyager Token" },
    { name: "VTHOUSDT", text: "VeThor Token" },
    { name: "XVSUSDT", text: "Venus" },
    { name: "VOXELUSDT", text: "Voxies" },
    /* W */
    { name: "WBTCUSDT", text: "Wrapped Bitcoin" },
    { name: "WOOUSDT", text: "WOO Network" },
    { name: "WINUSDT", text: "WINkLink" },
    { name: "WABIUSDT", text: "Wabi" },
    { name: "WAVESUSDT", text: "Waves" },
    { name: "WAXPUSDT", text: "WAX" },
    { name: "WRXUSDT", text: "WazirX" },
    { name: "WTCUSDT", text: "Waltonchain" },
    { name: "WANUSDT", text: "Wanchain" },
    { name: "WINGUSDT", text: "Wing Finance" },
    /* Y */
    { name: "YFIUSDT", text: "yearn.finance" }, 
    { name: "YGGUSDT", text: "Yield Guild Games" },
    /* X */
    { name: "XRPUSDT", text: "XRP" },
    { name: "XRPDOWNUSDT", text: "XRPDOWN" },
    { name: "XRPUPUSDT", text: "XRPUP" },
    /*Z */
    { name: "ZILUSDT", text: "Zilliqa" },
    { name: "ZECUSDT", text: "Zcash" },
    { name: "ZRXUSDT", text: "0x" },
    { name: "1INCHUSDT", text: "1inch Network" },
    /* { name: "USDT", text: "" },   */
]; 
export const timeIntervals = [
    { name: "1m", text: "1 min" },
    { name: "3m", text: "3 min" },
    { name: "5m", text: "5 min" },
    { name: "15m", text: "15 min" },
    { name: "30m", text: "30 min" },
    { name: "1h", text: "1 hour" },
    { name: "2h", text: "2 hours" },
    { name: "4h", text: "4 hours" },
    { name: "6h", text: "6 hours" },
    { name: "8h", text: "8 hours" },
    { name: "12h", text: "12 hours" },
    { name: "1d", text: "1 day" },
    { name: "3d", text: "3 days" },
    { name: "1w", text: "1 week" },
    { name: "1M", text: "1 month" }
];
export let indi = [
    { name: "sma()" },
    { name: "ema()" },
    { name: "lin()" },
    { name: "rsi()" },  
];
export const indilist = [
    { name: "vol()", text: "Annualized Historical Volatility" },
    { name: "sma()", text: "Simple Moving Average" },
    { name: "ema()", text: "Exponential Moving Average" },
    { name: "rsi()", text: "Relative Strength Index" },
    { name: "lin()", text: "Linear Regression" },
    { name: "lis()", text: "Linear Regression Slope" },
    { name: "lit()", text: "Linear Regression Intercept" },
    { name: "mac()", text: "Moving Average Convergence/Divergence" },
    { name: "cmo()", text: "Chande Momentum Oscillator" },
    { name: "hma()", text: "Hull Moving Average" },
    { name: "fos()", text: "Forecast Oscillator" },
    { name: "ede()", text: "Exponential Decay" },
    { name: "dpo()", text: "Detrended Price Oscillator" },
    { name: "kam()", text: "Kaufman Adaptive Moving Average" },
    { name: "dem()", text: "Double Exponential Moving Average" },//max 
    { name: "max()", text: "Maximum In Period" },
    { name: "min()", text: "Minimum In Period" },
    { name: "mod()", text: "Mean Deviation Over Period" },
    { name: "mom()", text: "Momentum" },
    { name: "msw()", text: "Mesa Sine Wave" },//bu indikato iki çıkışlı buna tekrar bak
    { name: "roc()", text: "Rate of Change" },
    { name: "ror()", text: "Rate of Change Ratio" },
    { name: "std()", text: "Standard Deviation Over Period" },
    { name: "sth()", text: "Stochastic RSI" },
    { name: "sum()", text: "Sum Over Period" },
    { name: "tem()", text: "Triple Exponential Moving Average" },
    { name: "trm()", text: "Triangular Moving Average" },
    { name: "trx()", text: "Trix" },
    { name: "tsf()", text: "Time Series Forecast" },
    { name: "vra()", text: "Variance Over Period" },
    { name: "vhf()", text: "Vertical Horizontal Filter" },
    { name: "wil()", text: "Wilders Smoothing" },
    { name: "wma()", text: "Weighted Moving Average" },
    { name: "zle()", text: "Zero-Lag Exponential Moving Average" },
];
export const inbot = [
    { name: "rsi()", text: "RSI" }, 
    { name: "lin()", text: "LİNREQ" },
    { name: "vol()", text: "Annualized Historical Volatility" },
    { name: "lis()", text: "Linear Regression Intercept" },
    { name: "mac()", text: "Moving Average Convergence/Divergence" },
    { name: "cmo()", text: "Chande Momentum Oscillator" },
    { name: "hma()", text: "Hull Moving Average" },
    { name: "fos()", text: "Forecast Oscillator" },
    { name: "ede()", text: "Exponential Decay" },
    { name: "dpo()", text: "Detrended Price Oscillator" },
    { name: "kam()", text: "Kaufman Adaptive Moving Average" },
    { name: "dem()", text: "Double Exponential Moving Average" },
    { name: "lit()", text: "Linear Regression Intercept" },
    { name: "max()", text: "Maximum In Period" },
    { name: "min()", text: "Minimum In Period" },
    { name: "mod()", text: "Mean Deviation Over Period" },
    { name: "mom()", text: "Momentum" },
    { name: "msw()", text: "Mesa Sine Wave" },
    { name: "roc()", text: "Rate of Change" },
    { name: "ror()", text: "Rate of Change Ratio" },
    { name: "std()", text: "Standard Deviation Over Period" },
    { name: "sth()", text: "Stochastic RSI" },
    { name: "sum()", text: "Sum Over Period" },
    { name: "tem()", text: "Triple Exponential Moving Average" },
    { name: "trm()", text: "Triangular Moving Average" },
    { name: "trx()", text: "Trix" },
    { name: "tsf()", text: "Time Series Forecast" },
    { name: "vra()", text: "Variance Over Period" },
    { name: "vhf()", text: "Vertical Horizontal Filter" },
    { name: "wil()", text: "Wilders Smoothing" },
    { name: "wma()", text: "Weighted Moving Average" },
    { name: "zle()", text: "Zero-Lag Exponential Moving Average" },
]